version: 0.2

phases:
    pre_build:
      commands:
      # install dependencies
      - echo Installing Dependencies ..................................
      - npm install
    build:
      commands:
        - echo Build starting ..................................
        - npm run build

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build